export const Codes = [
  {
    code: 'AF',
    country_code: '+93',
    country_name: 'Afghanistan',
    arab_name: 'أفغانستان',
  },
  {
    code: 'AL',
    country_code: '+355',
    country_name: 'Albania',
    arab_name: 'ألبانيا',
  },
  {
    code: 'DZ',
    country_code: '+213',
    country_name: 'Algeria',
    arab_name: 'الجزائر',
  },
  {
    code: 'AS',
    country_code: '+1684',
    country_name: 'American Samoa',
    arab_name: 'ساموا الأمريكية',
  },
  {
    code: 'AD',
    country_code: '+376',
    country_name: 'Andorra',
    arab_name: 'أندورا',
  },
  {
    code: 'AO',
    country_code: '+244',
    country_name: 'Angola',
    arab_name: 'أنغولا',
  },
  {
    code: 'AI',
    country_code: '+1264',
    country_name: 'Anguilla',
    arab_name: 'أنغيلا',
  },
  {
    code: 'AG',
    country_code: '+1268',
    country_name: 'Antigua & Barbuda',
    arab_name: 'أنتيغوا وبربودا',
  },
  {
    code: 'AM',
    country_code: '+374',
    country_name: 'Armenia',
    arab_name: 'أرمينيا',
  },
  {
    code: 'AR',
    country_code: '+54',
    country_name: 'Argentina',
    arab_name: 'الأرجنتين',
  },
  {
    code: 'AW',
    country_code: '+297',
    country_name: 'Europe',
    arab_name: 'أروبا',
  },
  {
    code: 'AU',
    country_code: '+61',
    country_name: 'Australia',
    arab_name: 'أستراليا',
  },
  {
    code: 'AT',
    country_code: '+43',
    country_name: 'Austria',
    arab_name: 'النمسا',
  },
  {
    code: 'AZ',
    country_code: '+994',
    country_name: 'Azerbaijan',
    arab_name: 'أذربيجان',
  },
  {
    code: 'BS',
    country_code: '+1242',
    country_name: 'Bahamas',
    arab_name: 'جزر البهاما',
  },
  {
    code: 'BH',
    country_code: '+973',
    country_name: 'Bahrain',
    arab_name: 'البحرين',
  },
  {
    code: 'BD',
    country_code: '+880',
    country_name: 'Bangladesh',
    arab_name: 'بنغلاديش',
  },
  {
    code: 'BB',
    country_code: '+1246',
    country_name: 'Barbados',
    arab_name: 'بربادوس',
  },
  {
    code: 'BY',
    country_code: '+375',
    country_name: 'Belarus',
    arab_name: 'بيلاروسيا',
  },
  {
    code: 'BE',
    country_code: '+32',
    country_name: 'Belgium',
    arab_name: 'بلجيكا',
  },
  {
    code: 'BZ',
    country_code: '+501',
    country_name: 'Belize',
    arab_name: 'بليز',
  },
  {
    code: 'BJ',
    country_code: '+229',
    country_name: 'Benin',
    arab_name: 'بنين',
  },
  {
    code: 'BM',
    country_code: '+1441',
    country_name: 'Bermuda',
    arab_name: 'برمودا',
  },
  {
    code: 'BT',
    country_code: '+975',
    country_name: 'Bhutan',
    arab_name: 'بوتان',
  },
  {
    code: 'BO',
    country_code: '+591',
    country_name: 'Bolivia',
    arab_name: 'بوليفيا',
  },
  {
    code: 'BA',
    country_code: '+387',
    country_name: 'Bosnia & Herzegovina',
    arab_name: 'البوسنة والهرسك',
  },
  {
    code: 'BW',
    country_code: '+267',
    country_name: 'Botswana',
    arab_name: 'بوتسوانا',
  },
  {
    code: 'BR',
    country_code: '+55',
    country_name: 'Brazil',
    arab_name: 'البرازيل',
  },
  {
    code: 'IO',
    country_code: '+246',
    country_name: 'British Indian Ocean Territory',
    arab_name: 'إقليم المحيط الهندي البريطاني',
  },
  {
    code: 'VG',
    country_code: '+1284',
    country_name: 'British Virgin Islands',
    arab_name: 'جزر فيرجن البريطانية',
  },
  {
    code: 'BN',
    country_code: '+673',
    country_name: 'Brunei',
    arab_name: 'بروناي',
  },
  {
    code: 'BG',
    country_code: '+359',
    country_name: 'Bulgaria',
    arab_name: 'بلغاريا',
  },
  {
    code: 'BF',
    country_code: '+226',
    country_name: 'Burkina Faso',
    arab_name: 'بوركينا فاسو',
  },
  {
    code: 'BI',
    country_code: '+257',
    country_name: 'Burundi',
    arab_name: 'بوروندي',
  },
  {
    code: 'KH',
    country_code: '+855',
    country_name: 'Cambodia',
    arab_name: 'كمبوديا',
  },
  {
    code: 'CM',
    country_code: '+237',
    country_name: 'Cameroon',
    arab_name: 'الكاميرون',
  },
  {
    code: 'CA',
    country_code: '+1',
    country_name: 'Canada',
    arab_name: 'كندا',
  },
  {
    code: 'CV',
    country_code: '+238',
    country_name: 'Cape Verde',
    arab_name: 'الرأس الأخضر',
  },
  {
    code: 'BQ',
    country_code: '+599',
    country_name: 'Caribbean Netherlands',
    arab_name: 'هولندا الكاريبية',
  },
  {
    code: 'KY',
    country_code: '+1345',
    country_name: 'Cayman Islands',
    arab_name: 'جزر كايمان',
  },
  {
    code: 'CF',
    country_code: '+236',
    country_name: 'Central African Republic',
    arab_name: 'جمهورية أفريقيا الوسطى',
  },
  {
    code: 'TD',
    country_code: '+235',
    country_name: 'Chad',
    arab_name: 'تشاد',
  },
  {
    code: 'CL',
    country_code: '+56',
    country_name: 'Chile',
    arab_name: 'تشيلي',
  },
  {
    code: 'CN',
    country_code: '+86',
    country_name: 'China',
    arab_name: 'الصين',
  },
  {
    code: 'CX',
    country_code: '+61',
    country_name: 'Christmas Island',
    arab_name: 'جزيرة الكريسماس',
  },
  {
    code: 'CC',
    country_code: '+61',
    country_name: 'Cocos (Keeling) Islands',
    arab_name: 'جزر كوكوس',
  },
  {
    code: 'CO',
    country_code: '+57',
    country_name: 'Colombia',
    arab_name: 'كولومبيا',
  },
  {
    code: 'KM',
    country_code: '+269',
    country_name: 'Comoros',
    arab_name: 'جزر القمر',
  },
  {
    code: 'CD',
    country_code: '+243',
    country_name: 'Congo (DRC)',
    arab_name: 'جمهورية الكونغو الديمقراطية',
  },
];
